{
    'name': 'Sale & Service Management',
    'version': '1.0',
    'summary': 'Complete example using ORM, relations, computed fields',
    'category': 'Sales',
    'author': 'Training Project',
    'depends': ['base', 'account'],
    'data': [
        'security/security.xml',
        'security/record_rules.xml',
        'security/ir.model.access.csv',
        'reports/sale_order_report.xml',
        'reports/sale_order_template.xml',
        'views/sale_order_views.xml',
        'views/sale_order_delivery_views.xml',
        'views/sale_order_dashboard.xml',
        'views/portal_orders_template.xml',
        'views/sale_order_template.xml',
    ],
    'application': True,
}